hibernate.connection.driver_class=org.postgresql.Driver
hibernate.connection.url=jdbc:postgresql://localhost:5432/new_db
hibernate.connection.username=postgres
hibernate.connection.password=20261
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=false
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update
hibernate.connection.CharacterEncoding=utf8
hibernate.generate_statistics=false
